name: Windows Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${env:GITHUB_REF#refs/*/}" >> $env:GITHUB_ENV
      - name: Debug - Check RELEASE_VERSION
        run: |
          echo "$env:RELEASE_VERSION"
          echo "${{ env.RELEASE_VERSION }}""
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Build
        run: |
          echo "Venv setup"
          python -m venv .venv
          .venv\Scripts\activate
          echo "Installing dependencies"
          pip install -e ./
          echo "Building style"
          python build_style.py
          echo "Building"
          cd .\scripts\
          .\build_win.bat
      - name: Zipping
        run: |
          echo "Zipping to Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip"
          Compress-Archive -Path ".\dist\release\" -DestinationPath "Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/release/Blender_Launcher_${{ env.RELEASE_VERSION }}_Windows_x64.zip